We only need xsltproc now instead of linking to the library. Also, any xslt will do so the user can specify a different command
git-svn-id: https://svn.code.sf.net/p/lurker/code/trunk@633 44f0b718-a8ad-45a4-bab0-870672037115

diff --git a/lurker/configure b/lurker/configure
--- a/lurker/configure
+++ b/lurker/configure
@@ -848,8 +848,9 @@ Optional Packages:
   --with-url              url location (default: http://this.host/lurker)
   --with-localedir        locale directory (default: DATADIR/locale)
   --with-dbdir            db directory (default: PREFIX/var/lib/lurker)
-  --with-stdir            st installation directory (default: none)
-  --with-cclientdir       c-client installation directory (default: none)
+  --with-stdir=DIR        st installation directory (default: none)
+  --with-cclientdir=DIR   c-client installation directory (default: none)
+  --with-xslt=CMD         Use the given command to render xslt
   --with-libiconv-prefix=DIR  search for libiconv in DIR/include and DIR/lib
   --with-included-gettext use the GNU gettext library included here
 
@@ -4977,17 +4978,19 @@ echo "$as_me: error: Unable to locate c-client header files" >&2;}
 
 
 
-  if test -z "$XSLT_CONFIG"; then
-    # Extract the first word of "xslt-config", so it can be a program name with args.
-set dummy xslt-config; ac_word=$2
+xsltengine="no"
+
+if test -n "$ac_tool_prefix"; then
+  # Extract the first word of "${ac_tool_prefix}xsltproc", so it can be a program name with args.
+set dummy ${ac_tool_prefix}xsltproc; ac_word=$2
 echo "$as_me:$LINENO: checking for $ac_word" >&5
 echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_XSLT_CONFIG+set}" = set; then
+if test "${ac_cv_path_xsltproc+set}" = set; then
   echo $ECHO_N "(cached) $ECHO_C" >&6
 else
-  case $XSLT_CONFIG in
+  case $xsltproc in
   [\\/]* | ?:[\\/]*)
-  ac_cv_path_XSLT_CONFIG="$XSLT_CONFIG" # Let the user override the test with a path.
+  ac_cv_path_xsltproc="$xsltproc" # Let the user override the test with a path.
   ;;
   *)
   as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
@@ -4997,62 +5000,99 @@ do
   test -z "$as_dir" && as_dir=.
   for ac_exec_ext in '' $ac_executable_extensions; do
   if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_XSLT_CONFIG="$as_dir/$ac_word$ac_exec_ext"
+    ac_cv_path_xsltproc="$as_dir/$ac_word$ac_exec_ext"
     echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
     break 2
   fi
 done
 done
 
-  test -z "$ac_cv_path_XSLT_CONFIG" && ac_cv_path_XSLT_CONFIG="no"
   ;;
 esac
 fi
-XSLT_CONFIG=$ac_cv_path_XSLT_CONFIG
+xsltproc=$ac_cv_path_xsltproc
 
-if test -n "$XSLT_CONFIG"; then
-  echo "$as_me:$LINENO: result: $XSLT_CONFIG" >&5
-echo "${ECHO_T}$XSLT_CONFIG" >&6
+if test -n "$xsltproc"; then
+  echo "$as_me:$LINENO: result: $xsltproc" >&5
+echo "${ECHO_T}$xsltproc" >&6
 else
   echo "$as_me:$LINENO: result: no" >&5
 echo "${ECHO_T}no" >&6
 fi
 
+fi
+if test -z "$ac_cv_path_xsltproc"; then
+  ac_pt_xsltproc=$xsltproc
+  # Extract the first word of "xsltproc", so it can be a program name with args.
+set dummy xsltproc; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_ac_pt_xsltproc+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $ac_pt_xsltproc in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_ac_pt_xsltproc="$ac_pt_xsltproc" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_ac_pt_xsltproc="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
   fi
+done
+done
 
-  if test "$XSLT_CONFIG" = "no" ; then
-     echo "*** The xslt-config script could not be found. Make sure it is"
-     echo "*** in your path, or set the XSLT_CONFIG environment variable"
-     echo "*** to the full path to xslt-config."
-     { { echo "$as_me:$LINENO: error: Need xslt to compile" >&5
-echo "$as_me: error: Need xslt to compile" >&2;}
+  test -z "$ac_cv_path_ac_pt_xsltproc" && ac_cv_path_ac_pt_xsltproc=""nil""
+  ;;
+esac
+fi
+ac_pt_xsltproc=$ac_cv_path_ac_pt_xsltproc
+
+if test -n "$ac_pt_xsltproc"; then
+  echo "$as_me:$LINENO: result: $ac_pt_xsltproc" >&5
+echo "${ECHO_T}$ac_pt_xsltproc" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+  xsltproc=$ac_pt_xsltproc
+else
+  xsltproc="$ac_cv_path_xsltproc"
+fi
+
+if test "x${xsltproc}" != "xnil"; then
+  xsltengine="${xsltproc} ../fmt/render-html.xsl -"
+fi
+
+
+# Check whether --with-xsltengine or --without-xsltengine was given.
+if test "${with_xsltengine+set}" = set; then
+  withval="$with_xsltengine"
+
+fi;
+
+if test "x${with_xsltengine}" != "x"; then
+  xsltengine="${with_xsltengine}"
+fi
+
+if test "x${xsltengine}" = "xno"; then
+ { { echo "$as_me:$LINENO: error: Some form of xslt tool must be available" >&5
+echo "$as_me: error: Some form of xslt tool must be available" >&2;}
    { (exit 1); exit 1; }; }
-  else
-     echo "$as_me:$LINENO: checking for libxslt" >&5
-echo $ECHO_N "checking for libxslt... $ECHO_C" >&6
-     xslt_CFLAGS=`$XSLT_CONFIG --cflags || echo no`
-     if test "x$RENDER_CFLAGS" = "xno"; then
-       { { echo "$as_me:$LINENO: error: Need xslt to compile" >&5
-echo "$as_me: error: Need xslt to compile" >&2;}
-   { (exit 1); exit 1; }; }
-     fi
-
-     xslt_LIBS=`$XSLT_CONFIG --libs || echo no`
-     if test "x$RENDER_LIBS" = "xno"; then
-       { { echo "$as_me:$LINENO: error: Need xslt to compile" >&5
-echo "$as_me: error: Need xslt to compile" >&2;}
-   { (exit 1); exit 1; }; }
-     fi
-
-     echo "$as_me:$LINENO: result: have it" >&5
-echo "${ECHO_T}have it" >&6
-
-     RENDER_CFLAGS="$RENDER_CFLAGS $xslt_CFLAGS"
-     RENDER_LIBS="$RENDER_LIBS $xslt_LIBS"
+fi
 
 
-
-  fi
+cat >>confdefs.h <<_ACEOF
+#define XSLT_ENGINE "${xsltengine}"
+_ACEOF
 
 
 
@@ -10301,9 +10341,8 @@ s,@CPP@,$CPP,;t t
 s,@ALLOCA@,$ALLOCA,;t t
 s,@STORAGE_LIBS@,$STORAGE_LIBS,;t t
 s,@STORAGE_CFLAGS@,$STORAGE_CFLAGS,;t t
-s,@XSLT_CONFIG@,$XSLT_CONFIG,;t t
-s,@RENDER_CFLAGS@,$RENDER_CFLAGS,;t t
-s,@RENDER_LIBS@,$RENDER_LIBS,;t t
+s,@xsltproc@,$xsltproc,;t t
+s,@ac_pt_xsltproc@,$ac_pt_xsltproc,;t t
 s,@build@,$build,;t t
 s,@build_cpu@,$build_cpu,;t t
 s,@build_vendor@,$build_vendor,;t t
