fix ordering bug + suse
git-svn-id: https://svn.code.sf.net/p/lurker/code/trunk@1095 44f0b718-a8ad-45a4-bab0-870672037115

diff --git a/lurker/configure b/lurker/configure
--- a/lurker/configure
+++ b/lurker/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CXXCPP EGREP LOCAL_MIMELIB JAM BINDIR LIBDIR INCDIR VARDIR ETCDIR DATADIR MANDIR LIBOBJS LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS CXX CXXFLAGS LDFLAGS CPPFLAGS ac_ct_CXX EXEEXT OBJEXT CXXCPP EGREP JAM LOCAL_MIMELIB BINDIR LIBDIR INCDIR VARDIR ETCDIR DATADIR MANDIR LIBOBJS LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -843,13 +843,13 @@ if test -n "$ac_init_help"; then
 Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
+  --with-zlib-include=DIR Location of zlib.h
+  --with-zlib-libname=LIB Try an alternative library name
   --with-mimelib-local    Use internal lurker/mimelib/*
   --with-mimelib-include=DIR
                           Location of mimelib/message.h
   --with-mimelib-libname=LIB
                           Try an alternative library name
-  --with-zlib-include=DIR Location of zlib.h
-  --with-zlib-libname=LIB Try an alternative library name
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -2463,6 +2463,251 @@ fi
 
 
 
+# Check whether --with-zlib-include or --without-zlib-include was given.
+if test "${with_zlib_include+set}" = set; then
+  withval="$with_zlib_include"
+
+else
+  with_zlib_include=""
+fi;
+
+echo "$as_me:$LINENO: checking for zlib.h" >&5
+echo $ECHO_N "checking for zlib.h... $ECHO_C" >&6
+if test "${ac_cv_header_zlib_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_header_search_save_CPPFLAGS=$CPPFLAGS
+ac_cv_header_zlib_h=no
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <zlib.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_zlib_h=standard
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+if test $ac_cv_header_zlib_h = no; then
+  for ac_inc in $with_zlib_include /usr/include /usr/local/include; do
+    CPPFLAGS="-I$ac_inc $ac_header_search_save_CPPFLAGS"
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <zlib.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
+  (eval $ac_compile) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest.$ac_objext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_header_zlib_h=-I$ac_inc
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest.$ac_ext
+  done
+fi
+CPPFLAGS=$ac_header_search_save_CPPFLAGS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_header_zlib_h" >&5
+echo "${ECHO_T}$ac_cv_header_zlib_h" >&6
+if test $ac_cv_header_zlib_h != no; then
+  test $ac_cv_header_zlib_h = standard || CPPFLAGS="$ac_cv_header_zlib_h $CPPFLAGS"
+
+else
+  { { echo "$as_me:$LINENO: error: Need zlib.h to compile" >&5
+echo "$as_me: error: Need zlib.h to compile" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+
+# Check whether --with-zlib-libname or --without-zlib-libname was given.
+if test "${with_zlib_libname+set}" = set; then
+  withval="$with_zlib_libname"
+
+else
+  with_zlib_libname=""
+fi;
+
+echo "$as_me:$LINENO: checking how gzFile f = gzdopen(0, \"r\") links" >&5
+echo $ECHO_N "checking how gzFile f = gzdopen(0, \"r\") links... $ECHO_C" >&6
+if test "${ac_cv_expression_gzFile_f___gzdopen_0___r__+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_expression_search_save_LIBS=$LIBS
+ac_cv_expression_gzFile_f___gzdopen_0___r__=no
+cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <zlib.h>
+int
+main ()
+{
+gzFile f = gzdopen(0, "r")
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_expression_gzFile_f___gzdopen_0___r__="standard"
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+if test "$ac_cv_expression_gzFile_f___gzdopen_0___r__" = "no"; then
+  for ac_lib in $with_zlib_libname zlib z libz; do
+    LIBS="-l$ac_lib  $ac_expression_search_save_LIBS"
+    cat >conftest.$ac_ext <<_ACEOF
+#line $LINENO "configure"
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <zlib.h>
+int
+main ()
+{
+gzFile f = gzdopen(0, "r")
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+         { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  ac_cv_expression_gzFile_f___gzdopen_0___r__=-l$ac_lib
+break
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+fi
+rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
+  done
+fi
+LIBS=$ac_expression_search_save_LIBS
+fi
+echo "$as_me:$LINENO: result: $ac_cv_expression_gzFile_f___gzdopen_0___r__" >&5
+echo "${ECHO_T}$ac_cv_expression_gzFile_f___gzdopen_0___r__" >&6
+if test "$ac_cv_expression_gzFile_f___gzdopen_0___r__" != "no"; then
+  test "$ac_cv_expression_gzFile_f___gzdopen_0___r__" = "standard" || LIBS="$ac_cv_expression_gzFile_f___gzdopen_0___r__ $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: Need zlib to link" >&5
+echo "$as_me: error: Need zlib to link" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+# Extract the first word of "jam", so it can be a program name with args.
+set dummy jam; ac_word=$2
+echo "$as_me:$LINENO: checking for $ac_word" >&5
+echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
+if test "${ac_cv_path_JAM+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  case $JAM in
+  [\\/]* | ?:[\\/]*)
+  ac_cv_path_JAM="$JAM" # Let the user override the test with a path.
+  ;;
+  *)
+  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
+for as_dir in $PATH
+do
+  IFS=$as_save_IFS
+  test -z "$as_dir" && as_dir=.
+  for ac_exec_ext in '' $ac_executable_extensions; do
+  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
+    ac_cv_path_JAM="$as_dir/$ac_word$ac_exec_ext"
+    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
+    break 2
+  fi
+done
+done
+
+  ;;
+esac
+fi
+JAM=$ac_cv_path_JAM
+
+if test -n "$JAM"; then
+  echo "$as_me:$LINENO: result: $JAM" >&5
+echo "${ECHO_T}$JAM" >&6
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
+if test "x${JAM}" = "x"; then
+  { { echo "$as_me:$LINENO: error: cannot build - jam required" >&5
+echo "$as_me: error: cannot build - jam required" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
 # Check whether --with-mimelib-local or --without-mimelib-local was given.
 if test "${with_mimelib_local+set}" = set; then
   withval="$with_mimelib_local"
@@ -2683,251 +2928,6 @@ fi
 fi
 LOCAL_MIMELIB=${LOCAL_MIMELIB}
 
-
-
-# Check whether --with-zlib-include or --without-zlib-include was given.
-if test "${with_zlib_include+set}" = set; then
-  withval="$with_zlib_include"
-
-else
-  with_zlib_include=""
-fi;
-
-echo "$as_me:$LINENO: checking for zlib.h" >&5
-echo $ECHO_N "checking for zlib.h... $ECHO_C" >&6
-if test "${ac_cv_header_zlib_h+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_header_search_save_CPPFLAGS=$CPPFLAGS
-ac_cv_header_zlib_h=no
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <zlib.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_header_zlib_h=standard
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-if test $ac_cv_header_zlib_h = no; then
-  for ac_inc in $with_zlib_include /usr/include /usr/local/include; do
-    CPPFLAGS="-I$ac_inc $ac_header_search_save_CPPFLAGS"
-    cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-$ac_includes_default
-#include <zlib.h>
-_ACEOF
-rm -f conftest.$ac_objext
-if { (eval echo "$as_me:$LINENO: \"$ac_compile\"") >&5
-  (eval $ac_compile) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest.$ac_objext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_header_zlib_h=-I$ac_inc
-break
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.$ac_objext conftest.$ac_ext
-  done
-fi
-CPPFLAGS=$ac_header_search_save_CPPFLAGS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_header_zlib_h" >&5
-echo "${ECHO_T}$ac_cv_header_zlib_h" >&6
-if test $ac_cv_header_zlib_h != no; then
-  test $ac_cv_header_zlib_h = standard || CPPFLAGS="$ac_cv_header_zlib_h $CPPFLAGS"
-
-else
-  { { echo "$as_me:$LINENO: error: Need zlib.h to compile" >&5
-echo "$as_me: error: Need zlib.h to compile" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-
-# Check whether --with-zlib-libname or --without-zlib-libname was given.
-if test "${with_zlib_libname+set}" = set; then
-  withval="$with_zlib_libname"
-
-else
-  with_zlib_libname=""
-fi;
-
-echo "$as_me:$LINENO: checking how gzFile f = gzdopen(0, \"r\") links" >&5
-echo $ECHO_N "checking how gzFile f = gzdopen(0, \"r\") links... $ECHO_C" >&6
-if test "${ac_cv_expression_gzFile_f___gzdopen_0___r__+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  ac_expression_search_save_LIBS=$LIBS
-ac_cv_expression_gzFile_f___gzdopen_0___r__=no
-cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <zlib.h>
-int
-main ()
-{
-gzFile f = gzdopen(0, "r")
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_expression_gzFile_f___gzdopen_0___r__="standard"
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-if test "$ac_cv_expression_gzFile_f___gzdopen_0___r__" = "no"; then
-  for ac_lib in $with_zlib_libname zlib z; do
-    LIBS="-l$ac_lib  $ac_expression_search_save_LIBS"
-    cat >conftest.$ac_ext <<_ACEOF
-#line $LINENO "configure"
-/* confdefs.h.  */
-_ACEOF
-cat confdefs.h >>conftest.$ac_ext
-cat >>conftest.$ac_ext <<_ACEOF
-/* end confdefs.h.  */
-#include <zlib.h>
-int
-main ()
-{
-gzFile f = gzdopen(0, "r")
-  ;
-  return 0;
-}
-_ACEOF
-rm -f conftest.$ac_objext conftest$ac_exeext
-if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
-  (eval $ac_link) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); } &&
-         { ac_try='test -s conftest$ac_exeext'
-  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
-  (eval $ac_try) 2>&5
-  ac_status=$?
-  echo "$as_me:$LINENO: \$? = $ac_status" >&5
-  (exit $ac_status); }; }; then
-  ac_cv_expression_gzFile_f___gzdopen_0___r__=-l$ac_lib
-break
-else
-  echo "$as_me: failed program was:" >&5
-sed 's/^/| /' conftest.$ac_ext >&5
-
-fi
-rm -f conftest.$ac_objext conftest$ac_exeext conftest.$ac_ext
-  done
-fi
-LIBS=$ac_expression_search_save_LIBS
-fi
-echo "$as_me:$LINENO: result: $ac_cv_expression_gzFile_f___gzdopen_0___r__" >&5
-echo "${ECHO_T}$ac_cv_expression_gzFile_f___gzdopen_0___r__" >&6
-if test "$ac_cv_expression_gzFile_f___gzdopen_0___r__" != "no"; then
-  test "$ac_cv_expression_gzFile_f___gzdopen_0___r__" = "standard" || LIBS="$ac_cv_expression_gzFile_f___gzdopen_0___r__ $LIBS"
-
-else
-  { { echo "$as_me:$LINENO: error: Need zlib to link" >&5
-echo "$as_me: error: Need zlib to link" >&2;}
-   { (exit 1); exit 1; }; }
-fi
-
-
-# Extract the first word of "jam", so it can be a program name with args.
-set dummy jam; ac_word=$2
-echo "$as_me:$LINENO: checking for $ac_word" >&5
-echo $ECHO_N "checking for $ac_word... $ECHO_C" >&6
-if test "${ac_cv_path_JAM+set}" = set; then
-  echo $ECHO_N "(cached) $ECHO_C" >&6
-else
-  case $JAM in
-  [\\/]* | ?:[\\/]*)
-  ac_cv_path_JAM="$JAM" # Let the user override the test with a path.
-  ;;
-  *)
-  as_save_IFS=$IFS; IFS=$PATH_SEPARATOR
-for as_dir in $PATH
-do
-  IFS=$as_save_IFS
-  test -z "$as_dir" && as_dir=.
-  for ac_exec_ext in '' $ac_executable_extensions; do
-  if $as_executable_p "$as_dir/$ac_word$ac_exec_ext"; then
-    ac_cv_path_JAM="$as_dir/$ac_word$ac_exec_ext"
-    echo "$as_me:$LINENO: found $as_dir/$ac_word$ac_exec_ext" >&5
-    break 2
-  fi
-done
-done
-
-  ;;
-esac
-fi
-JAM=$ac_cv_path_JAM
-
-if test -n "$JAM"; then
-  echo "$as_me:$LINENO: result: $JAM" >&5
-echo "${ECHO_T}$JAM" >&6
-else
-  echo "$as_me:$LINENO: result: no" >&5
-echo "${ECHO_T}no" >&6
-fi
-
-if test "x${JAM}" = "x"; then
-  { { echo "$as_me:$LINENO: error: cannot build - jam required" >&5
-echo "$as_me: error: cannot build - jam required" >&2;}
-   { (exit 1); exit 1; }; }
-fi
 
 prefix_backup="$prefix"
   exec_prefix_backup="$exec_prefix"
@@ -3667,8 +3667,8 @@ s,@EXEEXT@,$EXEEXT,;t t
 s,@OBJEXT@,$OBJEXT,;t t
 s,@CXXCPP@,$CXXCPP,;t t
 s,@EGREP@,$EGREP,;t t
-s,@LOCAL_MIMELIB@,$LOCAL_MIMELIB,;t t
 s,@JAM@,$JAM,;t t
+s,@LOCAL_MIMELIB@,$LOCAL_MIMELIB,;t t
 s,@BINDIR@,$BINDIR,;t t
 s,@LIBDIR@,$LIBDIR,;t t
 s,@INCDIR@,$INCDIR,;t t
